apiVersion: apps/v1
kind: Deployment
metadata:
  name: liatrio-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: liatrio-api
  template:
    metadata:
      labels:
        app: liatrio-api
    spec:
      containers:
      - name: liatrio-api
        image: woejood/liatrio-api:1.0.0
        #imagePullPolicy: Always
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: liatrio-api-service
spec:
  type: LoadBalancer
  ports:
  - port: 5000
  selector:
    app: liatrio-api